### ISSUE TITLE
Difficulties installing exact-cover using pip

### ISSUE THREAD

**Issue by johnrudge** [jwg4/exact_cover#57]
I'm running in to difficulties at the moment when installing the exact-cover package using pip. I noticed this first on google colab, which used to (version 1.0.0) install the exact-cover package just fine, by typing
`!pip install exact-cover`
 It would perform the installation using the binary wheel `exact_cover-1.0.0-cp38-cp38-manylinux_2_31_x86_64.whl`

Now, when the same command is typed two issues arise. First, for some reason it does not find a compatible binary wheel and so decides to install from the source distribution `exact_cover-1.1.0.tar.gz`. Second, while it claims to install from source fine, the actual module import in a python code fails with:
```
ModuleNotFoundError: No module named 'exact_cover_impl'
```
so the pip sdist install has not compiled the C code successfully. It would be really good to able to get `pip install` of this package working again!

**Comment by johnrudge** [comment]
I think the first issue is caused by a recent github update of `ubuntu-latest` to 22.04
https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/
I think this has a higher glibc version (2.35) than the older version (2.31), and I think the new version is not compatible with google colab. This should be easy to fix -- just compile binary packages with `ubuntu-20.04` instead.

The second issue, the failure of pip to install from sdist looks a trickier problem, but it would be nice to fix. It's confusing for users at the moment if pip says it has installed the package when it hasn't properly.

**Comment by jwg4** [comment]
I think you are right about the linux wheel compilation, and it can be fixed. Not sure about the other issue yet.
